### PR TITLE
Verbose flag

### LINKED ISSUE #109: [Feature suggestion] `--verbose` flag
I think the default user experience of running the CLI should be a relatively quiet install. A progress bar (e.g. [cli-progress](https://www.npmjs.com/package/cli-progress)) would be user friendly. The wall of text that currently gets generated is probably a bit overwhelming for a new user. For debugging, a `--verbose` flag could turn back on the outputs currently generated.

### PR DESCRIPTION
**Pull request by jessestorbeck**
Resolves #109. Adds default "quiet mode" for `install site`, `install experiment`, `prep`, and `start`. Use --verbose flag for additional output.

Additionally, experiment templates for lexical decision and grammaticality judgment are added back to the options in `install experiment`.

### CODE REVIEW

**Comment by hunterschep** [comment]
Testing the 'quiet' CLI:

- Test CLI runs as intended, displaying no output for installing site, experiment templates, and prep 
- All test commands (experiment, site, and prep) work with '--verbose' set 
- Data is viewable in postgres, and experiments work as intended

A couple small things:

- The console seems to log/spit out '--verbose flag set inside someFunction()' a lot, I don't know if this was intended?
- When quiet mode is set, especially on longer commands where there is simply nothing it could be a nice feature to have a progress percentage [XX%] like node/yarn/brew have featured as to let the user know that the cli is not hung on something

**Review by jkhartshorne — APPROVED** [review]
I read a lot of the code and spot-checked some things. It looks pretty good to me!

**Review by hunterschep — APPROVED** [review]
Testing the 'quiet' CLI:

Test CLI runs as intended, displaying no output for installing site, experiment templates, and prep

- All test commands (experiment, site, and prep) work with '--verbose' set
- Data is viewable in postgres, and experiments work as intended

A couple small things:

- The console seems to log/spit out '--verbose flag set inside someFunction()' a lot, I don't know if this was intended?
- When quiet mode is set, especially on longer commands where there is simply nothing it could be a nice feature to have a progress percentage [XX%] like node/yarn/brew have featured as to let the user know that the cli is not hung on something

**Review by ayang21 — APPROVED** [review]
The change worked for me!

**Pull request merged**
